### ISSUE TITLE
Option to disallow gap and/or N and/or non-AGTC ?

### ISSUE THREAD

**Issue by tseemann** [sanger-pathogens/snp-sites#28]
We are impressed by the speed of this tool (due to being C code).

A _very_ useful feature we need to the ability to also filter out things like:
- gap `-`
- `N`
- non-AGTC eg `*` and `X` etc

These would need to be independent options.

Ideally the current _default_ behaviour to remove conserved (monmorphic) sites could also be an option. eg. so we could remove all columns with a gap only and leave the rest.

**Comment by ONeillMB1** [comment]
Great tool! We also are very impressed with the speed! 

Building off the recommendation of @tseemann, it would also be nice to be able to impose thresholds for tolerable amounts of missing data. For example, if 75% of samples in the alignment have data and there exists a SNP among them, retain the data in the SNP alignment.

**Comment by andrewjpage** [comment]
I've added in a 'pure' mode as discussed with @tseemann and a 'keep monomorphic' mode (so it will work with BEAST).

**Comment by jamiethompson77** [comment]
This does work with amino acids though right?

**Comment by tseemann** [comment]
@jamiethompson77  i think AGTC is quite hard-coded into the tool, sorry.
