### ISSUE TITLE
segmentation fault in one fasta but not on the other

### ISSUE THREAD

**Issue by gnohls** [sanger-pathogens/snp-sites#53]
Hello, I am able to run snp-sites with one of my fasta files, but I get a segmentation fault when I try to run it with another one.

The output I get from gdb is
```
Core was generated by `snp-sites -mvp -o 8snps monoref_multi_8.fasta'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0 0x00007f6e8aa61827 in generate_snp_sites ()
    from /home/slh/.linuxbrew/cellar/snp-sites/2.2.0/lib/libsnp-sites.so.1
```

Any idea as to how to solve this?

Thanks!

**Comment by andrewjpage** [comment]
Hi, would it be possible for you to email the file which causes the error to path-help@sanger.ac.uk or put it on Dropbox/FTP and send us the location?

**Comment by gnohls** [comment]
Thank you for the quick response, here is the link to the fasta:
https://www.dropbox.com/s/ihmj6hftrho5a7i/monoref_multi_8.fasta?dl=0

**Comment by andrewjpage** [comment]
It looks like the file isnt an alignment:

Error in sequence Consensus_E2015018081.snps8.filtered. Size is 4857435 but expected 4857479
Error in sequence Consensus_E2015018082.snps8.filtered. Size is 4857435 but expected 4857479
Error in sequence Consensus_E2015018083.snps8.filtered. Size is 4857435 but expected 4857479
Error in sequence Consensus_E2015018084.snps8.filtered. Size is 4857435 but expected 4857479
Error in sequence Consensus_E2015018085.snps8.filtered. Size is 4858500 but expected 4857479
Error in sequence Consensus_E2015018086.snps8.filtered. Size is 4857434 but expected 4857479
Error in sequence Consensus_E2015018087.snps8.filtered. Size is 4857434 but expected 4857479
Error in sequence Consensus_E2015018088.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018089.snps8.filtered. Size is 4857435 but expected 4857479
Error in sequence Consensus_E2015018090.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018091.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018092.snps8.filtered. Size is 4857434 but expected 4857479
Error in sequence Consensus_E2015018093.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018094.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018095.snps8.filtered. Size is 4857434 but expected 4857479
Error in sequence Consensus_E2015018096.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018097.snps8.filtered. Size is 4857434 but expected 4857479
Error in sequence Consensus_E2015018098.snps8.filtered. Size is 4857436 but expected 4857479
Error in sequence Consensus_E2015018099.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018100.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018101.snps8.filtered. Size is 4857434 but expected 4857479
Error in sequence Consensus_E2015018102.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018103.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018104.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018105.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018106.snps8.filtered. Size is 4857435 but expected 4857479
Error in sequence Consensus_E2015018107.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018108.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018109.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018110.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018111.snps8.filtered. Size is 4857436 but expected 4857479
Error in sequence Consensus_E2015018112.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018113.snps8.filtered. Size is 4857434 but expected 4857479
Error in sequence Consensus_E2015018114.snps8.filtered. Size is 4857434 but expected 4857479
Error in sequence Consensus_E2015018115.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018116.snps8.filtered. Size is 4857435 but expected 4857479
Error in sequence Consensus_E2015018117.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018118.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018119.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018120.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018121.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018122.snps8.filtered. Size is 4857434 but expected 4857479
Error in sequence Consensus_E2015018123.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018124.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018125.snps8.filtered. Size is 4857434 but expected 4857479
Error in sequence Consensus_E2015018126.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018127.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018128.snps8.filtered. Size is 4857434 but expected 4857479
Error in sequence Consensus_E2015018129.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018130.snps8.filtered. Size is 4857433 but expected 4857479
Error in sequence Consensus_E2015018131.snps8.filtered. Size is 4857433 but expected 4857479

**Comment by gnohls** [comment]
I didn't expect that to happen but thank you!
On a side note, is the error log you posted part of any program? 
It seems very handy!

**Comment by andrewjpage** [comment]
Heres the script, it just loops over the sequences with BioPerl:
https://gist.github.com/andrewjpage/f3ef06826d1244b642ccce4c26846c05
