### ISSUE TITLE
Linuxbrew installation issue (links issue)

### ISSUE THREAD

**Issue by rbutleriii** [sanger-pathogens/snp-sites#54]
[rbutler@genomics 85]$ brew install snp-sites
==> Installing snp-sites from homebrew/science
==> Installing dependencies for homebrew/science/snp-sites: patchelf
==> Installing homebrew/science/snp-sites dependency: patchelf
==> Downloading https://linuxbrew.bintray.com/bottles/patchelf-0.9_1.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring patchelf-0.9_1.x86_64_linux.bottle.tar.gz
/home/rbutler/.linuxbrew/Cellar/patchelf/0.9_1: 6 files, 1.2M
==> Installing homebrew/science/snp-sites
==> Downloading https://linuxbrew.bintray.com/bottles-science/snp-sites-2.2.0.x86_64_linux.bottle.tar.gz
######################################################################## 100.0%
==> Pouring snp-sites-2.2.0.x86_64_linux.bottle.tar.gz
Error: An unexpected error occurred during the `brew link` step
The formula built, but is not symlinked into /home/rbutler/.linuxbrew
No such file or directory @ realpath_rec - /home/linuxbrew
Error: No such file or directory @ realpath_rec - /home/linuxbrew
[rbutler@genomics 85]$ brew update
Already up-to-date.
[rbutler@genomics 85]$ brew tap homebrew/science
[rbutler@genomics 85]$ brew install snp-sites
Warning: homebrew/science/snp-sites-2.2.0 already installed, it's just not linked

**Comment by andrewjpage** [comment]
This seems to be an issue with homebrew, so they might be best placed to help you with this.
