### ISSUE TITLE
Segmentation fault with larger sequences (on Desktop and HPC)

### ISSUE THREAD

**Issue by CMWbio** [sanger-pathogens/snp-sites#57]
Hi, 

I am running into a segmentation fault when calling the variants on a fasta with genome size > approx 9Mb (8Mb of the same fasta works fine).
Any thoughts as to why this is the case? I couldn't see a hard maximum genome length in the code.

edit: generating some test fastas with the included perl script reveals that it is an issue with the number of variants in the alignment, which makes sense.

Cheers 

Chris

**Comment by andrewjpage** [comment]
Hi Chris,
There is no hardcoded maximum genome length.  The largest I have ever passed in are 6Mbase genomes. The most number of samples has been about 10,000.  
I'm afraid I can't see your attached perl script?    
Regards,
Andrew

**Comment by andrewjpage** [comment]
Hi Chris,
I think I have identified the issue. Could you try out the latest version (2.3.3)?
Regards,
Andrew

**Comment by ChrisMWbiohub** [comment]
Hi Andrew
Thank you for the speedy reply, I have tested and the bug is solved (tested up to 50Mb total genome size).

Thanks 

Chris
