### ISSUE TITLE
segmentation fault with `-b` option

### ISSUE THREAD

**Issue by kwongj** [sanger-pathogens/snp-sites#58]
Version:  
```
$ snp-sites -V
snp-sites 2.3.2
```

No problems with standard usage e.g. outputting variant sites only.

On Linux:
```
$ snp-sites -b -o monomorphic.fa full.aln 
Segmentation fault (core dumped)
```

On MacOS:
```
$ snp-sites -b -o monomorphic.fa full.aln
Segmentation fault: 11
```

Is there a way to turn on a verbose or debugging mode?
I can supply the alignment file (multifasta) if needed. 13 sequences, each 1.89Mbp in length.

Thanks for your help.

**Comment by andrewjpage** [comment]
Hi Jason, It would be great to get a look at the alignment file. Thanks,
Andrew

**Comment by kwongj** [comment]
Thanks Andrew, have sent it to you on slack.

**Comment by andrewjpage** [comment]
I have fixed the issue in https://github.com/sanger-pathogens/snp-sites/pull/59 so pull down version 2.3.3

**Comment by kwongj** [comment]
Amazingly efficient! Thanks Andrew.
