### ISSUE TITLE
Segmentation error 

### ISSUE THREAD

**Issue by besnarda** [sanger-pathogens/snp-sites#78]
I am using snp-sites version 2.4.1, it is used in the snippy pipeline to detect snp in a full alignement. Error message from this pipeline is:

> snp-sites: symbol lookup error: snp-sites: undefined symbol: generate_snp_sites_with_ref_pure_mono
ERROR: Could not run: snp-sites -c -o 2_strains.aln 2_strains.full.aln

I have tried to launch again with only two strains and got a segmentation error

> snp-sites 2_strains.full.aln

Any ideas?

[2_strains.full.aln.zip](https://github.com/sanger-pathogens/snp-sites/files/3165493/2_strains.full.aln.zip)

**Comment by andrewjpage** [comment]
This is an error with your installation. I would recommend reinstalling it.
