### ISSUE TITLE
Is the reference genome used when using the snp-sites software?

### ISSUE THREAD

**Issue by youlijun** [sanger-pathogens/snp-sites#79]
Dear teacher：
I found snp-site very good, but I have doubts. The input file I am using is coregene.aln generated by roary. Does it use the reference genome?Without a reference genome, how does it find snp?
Thanks in advance

**Comment by andrewjpage** [comment]
More details are available in the paper http://mgen.microbiologyresearch.org/content/journal/mgen/10.1099/mgen.0.000056

You dont need a reference genome, if you 2 bases are different, then one of them must be a SNP.
