### ISSUE TITLE
Is there a sequence length limit? "Warning: No SNPs were detected so there is nothing to output."

### ISSUE THREAD

**Issue by FatihSarigol** [sanger-pathogens/snp-sites#80]
Hello,
I have an alignment file with full consensus genome sequences of 6 samples in exactly the same frames with the same number of bases without any blanks or indels but only with SNPs. And when I run snp-sites with default settings I get the error message:
"Warning: No SNPs were detected so there is nothing to output."

When I get the first 1000 bases for each sample without changing anything else in my file (for instance by doing cut -c1-1000) the program works and finds the SNPs; just stating so that it is clear that my installation and file formats work fine.

Samples have about 2.3 billion bases and I am working on an HPCC with over 500GB ram available and I don't get any other error related to memory. If you know the sequence length limit, could you please let me know so that I subset my file to the maximum length? 

Thanks!

**Comment by andrewjpage** [comment]
Theres no maximum length currently. There was a bug until about 2.5 years ago which limited very large alignments (v2.3.2 and below), so perhaps an update might solve it?  I've run it on files with 15 Gbases without any issue.
