### ISSUE TITLE
line 3030: syntax error near unexpected token `CHECK,check' on REHL 7.5

### ISSUE THREAD

**Issue by Aworwui** [sanger-pathogens/snp-sites#81]
Fails to build from the github download with the following error:

./configure: line 3030: syntax error near unexpected tokenCHECK,check'
./configure: line 3030: PKG_CHECK_MODULES(CHECK,check >= 0.8.2,have_check="yes",'checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
./configure: line 3030: syntax error near unexpected token `CHECK,check'
./configure: line 3030: `PKG_CHECK_MODULES(CHECK,check >= 0.8.2,have_check="yes",'

**Comment by andrewjpage** [comment]
The check library is missing, I'm afraid I dont know what the package is called in the RHEL world. You can try one of the other installation methods.
