### ISSUE TITLE
Problem with installation via Bioconda

### ISSUE THREAD

**Issue by Martinique-F** [sanger-pathogens/snp-sites#83]
Hi!
I just tried to install snp-sites using Bioconda and get the following message:  

**UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: snp-sites
  channel url: https://conda.anaconda.org/snp-sites
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.**  

I copied the url into my browser but its not available there..  

Best,
Martinique

**Comment by puethe** [comment]
Hi Martinique,
what command do you use? You should be able to install snp-sites with the commands shown [here](https://anaconda.org/bioconda/snp-sites). If you haven't enabled the bioconda channel yet, you'll need to run `conda config --add channels bioconda` first.
Cheers,
Christoph

**Comment by Martinique-F** [comment]
Hi Christoph,


thank you for the quick answer. It now worked just fine.

Have a nice wekend,

Martinique

 

 



Gesendet: Donnerstag, 15. August 2019 um 15:53 Uhr
Von: "Christoph Püthe" <notifications@github.com>
An: sanger-pathogens/snp-sites <snp-sites@noreply.github.com>
Cc: Martinique-F <martinique.frentrup@web.de>, Author <author@noreply.github.com>
Betreff: Re: [sanger-pathogens/snp-sites] Problem with installation via Bioconda (#83)


Hi Martinique,
what command do you use? You should be able to install snp-sites with the commands shown here. If you haven't enabled the bioconda channel yet, you'll need to run conda config --add channels bioconda first.
Cheers,
Christoph
